---
title: "Viz"
author: "Sílvia Majó-Vázquez"
date: "10/13/2017"
output:
  html_document: default
  pdf_document: default
---

```{r}
rm(list=ls())
gapminder_file <- "https://raw.githubusercontent.com/COMBINE-Australia/RNAseq-R/gh-pages/data/gapminder-FiveYearData.csv"
download.file(gapminder_file, destfile="gapminder-FiveYearData.csv")
gapminder <- read.csv("gapminder-FiveYearData.csv")
head(gapminder)
ggplot(data=gapminder, aes(x=gdpPercap, y=lifeExp))+geom_point()
g<-ggplot(data=gapminder, aes(x=year, y=lifeExp))+geom_point()
pdf(file="g.pdf", width=3, height = 4)
g
dev.off()
getwd ()

ggplot(data = gapminder, aes(x=year, y=lifeExp, by=country, color=continent)) +
geom_line()

ggplot(data = gapminder, aes(x=year, y=lifeExp, by=country)) +
  geom_point()+geom_line(aes(color=continent)) 
```

```{r}
ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp, color=continent)) +geom_point(alpha = 0.5) + scale_x_log10()
```

```{r}
ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp)) +
  geom_point(alpha = 0.5) + scale_x_log10() + geom_smooth(method="lm")
```

```{r}
ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp, color=continent)) +geom_point(alpha = 0.5) + scale_x_log10() + facet_wrap (~continent)+ theme_classic()
```

```{r}
starts.with <- substr(gapminder$country, start = 1, stop = 1)
starts.with 
az.countries <- gapminder[starts.with %in% c("A", "Z"), ]
az.countries 

ggplot(data = az.countries, aes(x = year, y = lifeExp, color=continent)) +
  geom_line() + facet_wrap( ~ country)
```


```{r}
ggplot(data = az.countries, aes(x = year, y = lifeExp, color=continent)) +
  geom_line() + facet_wrap( ~ country) +
  labs(
    x = "Year",              # x axis title
    y = "Life expectancy",   # y axis title
    title = "Figure 1",      # main title of figure
    color = "Continent"      # title of legend
  ) +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank())
```

